config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'chatroom#index'
  get 'login' ,to: 'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true,uniqueness: {case_sensitive: false},length: {minimum: 3, maximum: 15}
  has_secure_password
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user,:logged_in?
  
  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
    
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:error]="You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  
  def index
    @messages=Message.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :login_redirect ,only: [:new,:create]
  
  def new
    
  end
  
  def create
    user=User.find_by(username: params[:session][:username])
    if user and user.authenticate(params[:session][:password])
      session[:user_id]=user.id
      flash[:success]='You have successfully logged in'
      redirect_to root_path
    else
      flash.now[:error]='You have incorrect email or password'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id]=nil
    flash[:success]='You have successfully logged out'
    redirect_to login_path
  end
  
  private
  
  def login_redirect
    if logged_in?
      flash[:error]='You are already logged in'
      redirect_to root_path
    end
  end
    
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular coffee orange icon"></i>
  Friends
</h2>

<div class="ui two coulmn grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">    
        <div class="ui feed">
          <%= render @messages %>

        </div>
      </div>
      <div class="extra content">
        <form class="ui reply form">
          <div class="field">
            <div class="ui fluid icon input">
              <input type='text' placeholder='Enter a message...'>
                <i class="bordered inverted orange edit icon"></i>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>   
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type,message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
      <div class="header">
        <%= message_content %>
      </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to 'Chatroom',root_path, class: "active item" %>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to 'Log out',logout_path, method: :delete,class: 'item' %>
      <% else %>
        <%= link_to 'Log in', login_path, :class=> 'item' %>
      <% end %>
    </div>
  </div>
  <% if !logged_in? %>
  
    <div class="item">
        <%= link_to 'Log in', login_path, class: 'ui primary button' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>    
      </div>
    </div>
    <div class='ui container'>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em> :  <%= message.body %>
    </div>
  </div>
</div>